version: "3.8"

services:
  #`postgres:` определяет сервис для базы данных PostgreSQL в файле Docker Compose.
  postgres:
    container_name: postgres
    env_file: postgres.env
    image: postgres:alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"
    ports:
      - "5432:5432"
    shm_size: 256mb
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"

networks:
  default:
    external: true
    name: $NETWORK
