#`version: "3.5"` указывает версию формата файла Docker Compose, который будет использоваться. В данном случае это версия 3.5. Эта версия поддерживает такие возможности, как объекты `config`, `секреты` и опции `deploy` для развертывания сервисов в рое.
version: "3.5"

#Это определение сети под названием "docker_lasp" с именем сети по умолчанию. Эта сеть может использоваться для соединения различных служб, определенных в файле Docker Compose, позволяя им взаимодействовать друг с другом.
networks:
  docker_lasp:
    name: $DEFAULT_NETWORK

services:
  #`postgres:` определяет сервис для базы данных PostgreSQL в файле Docker Compose.
  postgres:
    #`env_file: - "postgres.env"` указывает путь к файлу "postgres.env", который содержит переменные окружения, используемые службами `postgres` и `redis`. Эти переменные окружения могут использоваться для настройки различных параметров служб, таких как учетные данные базы данных и параметры подключения.
    env_file:
      - "postgres.env"
    #`image: postgres:15.2` указывает образ Docker, который будет использоваться для службы `postgres` с версией 15.2 системы управления базами данных PostgreSQL.
    image: postgres:15.2
    #`shm_size: 256mb` устанавливает размер общей памяти для службы `postgres` в 256 мегабайт. Это используется для повышения производительности, позволяя PostgreSQL использовать общую память для определенных операций.
    shm_size: 256mb
    #`ports: - "5432:5432"` открывает порт 5432 контейнера службы `postgres` для хост-машины, позволяя внешним приложениям подключаться к базе данных PostgreSQL, запущенной внутри контейнера. Первое число (5432) - это номер порта на хост-машине, а второе число (также 5432) - это номер порта внутри контейнера.
    ports:
      - "5432:5432"
    #`restart: always` - это опция конфигурации в Docker Compose, которая указывает, что контейнер всегда должен перезапускаться, если он останавливается по какой-либо причине, например, в результате сбоя или ручной остановки. Это гарантирует, что служба всегда будет доступна и запущена, даже в случае непредвиденных сбоев.
    restart: always
    #`volumes: - "./postgres/data:/var/lib/postgresql/data"` создает постоянный том для службы `postgres`. Он отображает каталог `./postgres/data` на хост-машине на каталог `/var/lib/postgresql/data` внутри контейнера. Это позволяет сохранять данные, хранящиеся в базе данных PostgreSQL, даже если контейнер остановлен или удален.
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    #`container_name: postgres` - это установка имени контейнера для службы `postgres` на "postgres". Это позволяет легко идентифицировать контейнер и управлять им с помощью команд Docker.
    container_name: postgres
    #`networks: - "docker_lasp"` определяет сеть под названием "docker_lasp" и подключает все сервисы (postgres, pgadmin и redis) к этой сети. Это позволяет службам взаимодействовать друг с другом, используя имена своих контейнеров в качестве имен хостов, не открывая свои порты для хост-машины или других внешних сетей.
    networks:
      - "docker_lasp"